variables:
  project_name: 'fiap-azure-green-api'
  netcore_version: '2.2'
  project_test: 'fiap-azure-green-api-tests'

jobs:
- job: Build
  steps:
  - script: |
      pwd && ls -la
      dotnet restore 
      dotnet publish -c Release -o bin/Release/netcoreapp$(netcore_version)
      mkdir artifact
      cp -r $(project_name)/bin/Release/netcoreapp$(netcore_version) artifact/$(Build.SourceBranchName)
    displayName: Build Application
  - task: PublishPipelineArtifact@1
    displayName: Store Application Artifact
    inputs:
      path: $(System.DefaultWorkingDirectory)/artifact
      artifact: $(project_name)

- job: Restore
  steps:
  - script: |
      pwd && ls -la
      dotnet restore
    displayName: Restore

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure para Estudantes(039815ad-a7ab-4597-b4d9-52175fcd19ed)'
      appType: 'webAppLinux'
      WebAppName: 'fiap-azure-green-api'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
      StartupCommand: 'doente run'